##############################################################################################################################################################
#Econ 485 
#"“The curious task of economics is to demonstrate to men how little they really know about what they imagine the can design.” 
  # F. A. Hayek, The Fatal Conceit: The Errors of Socialism

#The following code wrote by Tie 
  # The following code, including
    #1.1 seasonally adjusted unemployment rate in Canada (2018-2022) monetarily
      #1.1.1 the standard plot method
      #1.1.2 the YOY growth rate method (not helpful)
    #1.2 Job vacancies, payroll employees, and job vacancy rate, by economic regions, quarterly, adjusted for seasonality
      #note: The jobs could be full-time, part-time, permanent, temporary, casual, or seasonal.
      #1.2.1 the standard plot method
      #1.2.2 the YOY growth rate method
    #1.3 Wages, salaries and employers' social contributions monthly from 2018-2022
      #1.3.1the normally plot method
      #1.3.2 the YOY growth rate method

#the following data will be available in a group Excel file
  #due to my poor understanding of the usage of OECD, therefore OECD data will include in excel
    #Copy of The export change for CA, UK, US, EU AND CN
    #The monthly imports (growth on the same period of the previous year)
  #The following data was collected from the Bank of Canada
    #The government bond yield 
    #from short to long
    #Can Consumer Expectations

#############################################################################################################################################################


  rm(list = ls())
  #make sure everthing will be fine.

  #set the working directory
  setwd("")
  
  #create a new file for all the generated by the graphy
  dir.create("pics")
  
  install.packages("writexl")
  
#Step one Lode the all package that necessary. 
library (lubridate)    
library (cansim)       
library (OECD)        
library (WDI)          
library (fredr)        
library (mFilter)      
library (neverhpfilter)
library (tsbox)
library (RColorBrewer) #so sad they do not have colorful black 
library(plotly)
library(wesanderson)
  library("writexl")
  

#1 The labor data
  #1.1 Labor force characteristics, monthly, seasonally adjusted and trend-cycle
    #unemployment seasonally adjusted (2018-2022)
  #https://www150.statcan.gc.ca/n1/daily-quotidien/220909/dq220909a-eng.htm?indid=3587-2&indgeo=0
    #the report wrote by the statistics Canada
  #get the data form statistic Canada
  unemployment_rate_raw <- "v2062815"
  unemployment.st <- get_cansim_vector(unemployment_rate_raw, start_time = "2018-01-01")
  unemployment_rate_year.st <- year(unemployment.st$REF_DATE[1])
  unemployment_rate_month.st <- month(unemployment.st$REF_DATE[1])
  
  #transfer data to the time series time
  c(unemployment_rate_year.st, unemployment_rate_month.st)
  unemployment_rate.ts<- ts(unemployment.st$VALUE, start = c(unemployment_rate_year.st, unemployment_rate_month.st), freq = 12)
  #now its time series data!

  
  plot(unemployment_rate.ts, col= "#003B6F",lwd=2.4)
  #draw the data, color and the wide of the line
  legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F")) #Tardis blue
  
  #saving the graph
  #It just same things,I specific write it again because I can just copy and paste it again...
  pdf("pics/CA_unemployment_rate_plot.pdf", height = 9, width = 12)
  plot(unemployment_rate.ts, col= "#003B6F",lwd=2.4, 
       main = 'Canadian unemployment rate 2018-2022', ylab = 'unemployment rate', xlab = 'years')
  legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F"))
  dev.off()
  
  #the YoY Growth Rate 
  unemployment_rate.yoy <- diff(log(unemployment_rate.ts), 12)
  plot(unemployment_rate.yoy, type = "l",col= "#003B6F",lwd=2.4, 
       main = 'Canadian unemployment rate change 2018-2022', ylab = 'the percantage change', xlab = 'time')
  abline(h = 0)
  rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
  #p/l/b/o/s/h/n
  #Points plot (default)/Line plot/Both (points and line)/Both (overplotted)/Both (overplotted)/Histogram-like plot/No plotting
  
  pdf("pics/CA_unemployment_rate_YOY.pdf", height = 9, width = 12)
  plot(unemployment_rate.yoy, type = "l",col= "#003B6F",lwd=2.4, 
       main = 'Canadian unemployment rate change 2018-2022', ylab = 'the percantage change', xlab = 'time')
  abline(h = 0)
  rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
  legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F"))
  dev.off()
  
  rm(list = ls())

  
  #1.2 The Job vacancy rate in Canada unadjusted for seasonality
  

  CA_Job_vacancy_rate_raw<- "v1374464762"
  CA_Job_vacancy_rate <- get_cansim_vector(CA_Job_vacancy_rate_raw, start_time = "2017-01-01")

  CA_Job_vacancy_rate_year.st <- year(CA_Job_vacancy_rate$REF_DATE[1])
  CA_Job_vacancy_rate_month.st <- month(CA_Job_vacancy_rate$REF_DATE[1])
  
  #transfer data to the time series time
  c(CA_Job_vacancy_rate_year.st, CA_Job_vacancy_rate_month.st)
  CA_Job_vacancy_rate.ts<- ts (CA_Job_vacancy_rate$VALUE, 
                            start = c(CA_Job_vacancy_rate_year.st, CA_Job_vacancy_rate_month.st), 
                            freq = 4)
  ## frequence: 12
  #12 is for the monthly data 
  #1 is for the yearly data
  #4 is for the quarterly data
  #52 for the weekly data
  #356.25 is for the daily data
  #now its time series data!
  
  plot(CA_Job_vacancy_rate.ts)
  
  #saving the graph
  #It just same things,I specific write it again because I can just copy and paste it again...
  pdf("pics/CA_Job_vacancy_rate_plot.pdf", height = 9, width = 12)
  plot(CA_Job_vacancy_rate.ts, col= "#003B6F",lwd=2.4, 
       main = 'Canada_Job_vacancy_rate_quarterly_2018-2022', ylab = 'rate', xlab = 'time')
  legend('topleft', lty=1,lwd=2.4, legend= c('Job_vacancy_rate'), col = c("#003B6F"))
  dev.off()
  
  #the YoY Growth Rate 
  CA_Job_vacancy_rate.yoy <- diff(log(CA_Job_vacancy_rate.ts), 4)
  plot(CA_Job_vacancy_rate.yoy, type = "l",col= "#003B6F",lwd=2.4, 
       main = 'Canada Job vacancy rate quarterly 2018-2022', ylab = 'rate', xlab = 'time')
  abline(h = 0)
  rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")

  
  pdf("pics/CA_Job_vacancy_rate_YOY.pdf", height = 9, width = 12)
  plot(CA_Job_vacancy_rate.yoy, type = "l",col= "#003B6F",lwd=2.4, 
       main = 'Canada Job vacancy rate quarterly 2018-2022', ylab = 'rate', xlab = 'time')
  abline(h = 0)
  rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
  legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F"))
  dev.off()
  
  rm(list = ls())
  
  #1.3 Wages, salaries and employers' social contributions monthly from 2018-2022
  CA_wage_and_Salaries_raw <- "v1996532"
  CA_wage_and_Salaries.st <- get_cansim_vector(CA_wage_and_Salaries_raw, start_time = "2018-01-01")
  CA_wage_and_Salaries_year.st <- year(CA_wage_and_Salaries.st$REF_DATE[1])
  CA_wage_and_Salaries_month.st <- month(CA_wage_and_Salaries.st$REF_DATE[1])
  
  #transfer data to the time series time
  c( CA_wage_and_Salaries_year.st,  CA_wage_and_Salaries_month.st)
  CA_wage_and_Salaries.ts<- ts(CA_wage_and_Salaries.st$VALUE,
                               start = c(CA_wage_and_Salaries_year.st, CA_wage_and_Salaries_month.st),
                               freq = 12)
  #now its time series data!
  
  #the YoY Growth Rate 
  CA_wage_and_Salaries.yoy <- diff(log( CA_wage_and_Salaries.ts), 12)
  
  pdf("pics/CA_wage_and_Salaries_YOY.pdf", height = 9, width = 12)
  plot(CA_wage_and_Salaries.yoy, type = "l",col= "#003B6F",lwd=2.4, 
       main = 'Canadian wage and salaries change monthly 2018-2022', ylab = 'the percantage change', xlab = 'time')
  abline(h = 0)
  rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
  legend('topleft', lty=1,lwd=2.4, legend= c('the percentage of change'), col = c("#003B6F"))
  dev.off()
  #note: that gain gap due to may people lost their job...
  #I really should compare this to inflation..
  
  rm(list = ls())

  #now I can finally rest in peace.
